#!/bin/bash

#__author__ = "Thomas Storm, Hans Permana, and Martin Boettcher, Brockmann Consult GmbH"
#__copyright__ = "Copyright 2018, Brockmann Consult GmbH"
#__license__ = "For use with Calvalus processing systems"
#__version__ = "1.1"
#__email__ = "info@brockmann-consult.de"
#__status__ = "Production"

# changes in 1.1
# Adaptations for basic authentication in ESTHub

#set -x

WPS_BASE_URL=https://ehgateway.maaamet.ee/wps/calvalus

USERNAME=$1
ACTION=$2
PARAMETER=$3

if [[ $1 == "-h" || $2 == "" ]] ; then
  echo "Usage: wpsclient username action <JobId|requestXml>"
  echo "    action MUST be one of GetCapabilities DescribeProcess Execute GetStatus FetchResults"
  echo "        GetCapabilities: Provides the capabilities of the CODE-DE WPS interface"
  echo "        DescribeProcess: Prints formal paramters of a processor of the CODE-DE processing system"
  echo "        Execute: Submits the given processing request to the CODE-DE processing system"
  echo "        GetStatus: Submits the given processing request to the CODE-DE processing system"
  echo "        FetchResult: Downloads the result of the given URL"
  echo "    if action is Execute, you MUST provide requestXml as 3rd parameter"
  echo "    if action is GetStatus, you MUST provide JobId as 3dr parameter"
  echo "    if action is FetchResult, you MUST provide a URL you got from GetStatus after successful processing as 3rd parameter"
  echo "Requires: a password file named .<username> with just the password"
  exit 0
fi

if [ ! -e .${USERNAME} ]; then
    echo "missing password file .${USERNAME}"
    exit 1
fi
PASSWORD=$(cat .${USERNAME})
if [ "${PASSWORD:0:12}" = "srcpassword=" ]; then
    . .${USERNAME}
    PASSWORD="$srcpassword"
fi
if [ "$PASSWORD" == "" ]; then
    echo "empty password file .${USERNAME}"
    exit 1
fi

urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    # You can either set a return variable (FASTER)
  REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
}

if [[ ${ACTION} == "GetCapabilities" ]] ; then
    URL="${WPS_BASE_URL}?Service=WPS&Version=1.0.0&Request=GetCapabilities"
elif [[ ${ACTION} == "DescribeProcess" ]] ; then
    if [ "${PARAMETER}" = "" ]; then
        PARAMETER=all
    fi
    URL="${WPS_BASE_URL}?Service=WPS&Version=1.0.0&Request=DescribeProcess&Version=1.0.0&Identifier=$(urlencode ${PARAMETER})"
elif [[ ${ACTION} == "Execute" ]] ; then
    URL="${WPS_BASE_URL}"
elif [[ ${ACTION} == "GetStatus" ]] ; then
    URL="${WPS_BASE_URL}?Service=WPS&Version=1.0.0&Request=GetStatus&JobId=$(urlencode ${PARAMETER})"
elif [[ ${ACTION} == "FetchResult" ]] ; then
    URL=$(echo "$PARAMETER" | sed 's/http:/https:/' | sed 's/:80\//\//')
fi

if [ ${ACTION} = Execute ] ; then
    curl -u ${USERNAME}:${PASSWORD} -L -H "Content-Type:application/xml" -d "@$PARAMETER" "${URL}"
elif [ ${ACTION} = FetchResult ] ; then
    curl -u ${USERNAME}:${PASSWORD} -s -S -L -O ${URL}
else
    set -x
    curl -u ${USERNAME}:${PASSWORD} -s -S -L ${URL}
fi

