--- Makefile	2013-02-21 23:50:45.000000000 +0100
+++ Makefile	2013-02-27 11:46:41.000000000 +0100
@@ -6,7 +6,7 @@
 LEVEL1_MERIS=yes
 DEBUG=no
 
-FLAGS = -Wall -I/usr/include/hdf/
+FLAGS = -Wall -I/home/marcoz/Workspace/OC/build/include -L/home/marcoz/Workspace/OC/build/lib
 
 ifeq ($(DEBUG),yes)
 	FLAGS += -DVERBOSE # verbose mode
@@ -32,8 +32,9 @@
 #  LIBS += $(wildcard /usr/lib/libdf.a /usr/lib64/hdf/libdf.a)
 LIBS = -lgsl -lgslcblas -ljpeg -lz -ldf -lmfhdf
 ifeq ($(NETCDF),yes)
-	LIBS += -lnetcdf
+	LIBS += -lhdf5_hl -lhdf5 -lnetcdf
 endif
+SLIBS = -Wl,--start-group $(LIBS) -Wl,--end-group -Wl,--wrap=memcpy
 
 EXEC = polymer
 LIBNAME = libpolymer.a
@@ -78,6 +79,7 @@
 SRC_LIB = odesa_polymer.cpp
 
 OBJ = $(SRC:%.cpp=$(DIROBJ)/%.o)
+OBJ_MEM = $(DIROBJ)/memcpy.o
 OBJ_EXE = $(SRC_EXE:%.cpp=$(DIROBJ)/%.o)
 OBJ_LIB = $(SRC_LIB:%.cpp=$(DIROBJ)/%.o)
 
@@ -101,9 +103,9 @@
 init:
 	mkdir -p $(DIROBJ)
 
-exe: init $(EPR_OBJ) $(OBJ_EXE) $(OBJ)
+exe: init $(EPR_OBJ) $(OBJ_EXE) $(OBJ) $(OBJ_MEM)
 	@echo Building executable...
-	$(CPPCOMP) -o $(EXEC) $(CPPFLAGS) $(OBJ) $(OBJ_EXE) $(EPR_OBJ) $(LIBS)
+	$(CPPCOMP) --verbose -o $(EXEC) $(CPPFLAGS) $(OBJ) $(OBJ_EXE) $(OBJ_MEM) $(EPR_OBJ) $(SLIBS)
 
 $(DIROBJ)/%.o: $(DIRSRC)/%.cpp $(DIRSRC)/%.h
 	@mkdir -p $(dir $@)
@@ -112,6 +114,8 @@
 	$(CPPCOMP) -c -o $@ $(CPPFLAGS) $<
 $(DIROBJ)/%.o: $(EPR_DIRSRC)/%.c
 	$(CCOMP) -c -o $@ $(CFLAGS) $<
+$(DIROBJ)/%.o: memcpy.c
+	$(CCOMP) -c -o $@ $<
 
 clean:
 	rm -fv $(EXEC)
--- /dev/null	2013-02-27 08:53:49.883974085 +0100
+++ memcpy.c	2013-02-27 11:40:41.000000000 +0100
@@ -0,0 +1,9 @@
+#include <string.h>
+
+/* some systems do not have newest memcpy@@GLIBC_2.14 - stay with old good one */
+asm (".symver memcpy, memcpy@GLIBC_2.2.5");
+
+void *__wrap_memcpy(void *dest, const void *src, size_t n)
+{
+    return memcpy(dest, src, n);
+}
\ Kein Zeilenumbruch am Dateiende.
