//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 03:37:15 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/wps/1.0.0",
            elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
            xmlns={@XmlNs(prefix="wps", namespaceURI="http://www.opengis.net/wps/1.0.0"),
                   @XmlNs(prefix="ows", namespaceURI="http://www.opengis.net/ows/1.1")})
package com.bc.calvalus.wps2.jaxb;

import javax.xml.bind.annotation.XmlNs;