//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.12 at 04:40:22 PM CEST 
//


package com.bc.calvalus.wpsrest.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
            "planetaryGrid",
            "numRows",
            "compositingType",
            "superSampling",
            "maskExpr",
            "variables",
            "aggregators",
            "postProcessor",
            "minDataHour",
            "metadataAggregatorName",
            "startDateTime",
            "periodDuration",
            "timeFilterMethod",
            "outputFile"
})
@XmlRootElement(name = "parameters", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
public class L3Parameters {

    @XmlElement(name = "planetaryGrid", defaultValue = "org.esa.beam.binning.support.SEAGrid", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected String planetaryGrid;
    @XmlElement(name = "numRows", defaultValue = "2160", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected int numRows;
    @XmlElement(name = "compositingType", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected CompositingType compositingType;
    @XmlElement(name = "superSampling", defaultValue = "1", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected Integer superSampling;
    @XmlElement(name = "maskExpr", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected String maskExpr;
    @XmlElement(name = "variables", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected Variables variables;
    @XmlElement(name = "aggregators", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected Aggregators aggregators;
    @XmlElement(name = "postProcessor", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected CellProcessorConfig postProcessor;
    @XmlElement(name = "minDataHour", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected Double minDataHour;
    @XmlElement(name = "metadataAggregatorName", defaultValue = "FIRST_HISTORY", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected String metadataAggregatorName;
    @XmlElement(name = "startDateTime", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected String startDateTime;
    @XmlElement(name = "periodDuration", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected Double periodDuration;
    @XmlElement(name = "timeFilterMethod", defaultValue = "NONE", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected TimeFilterMethod timeFilterMethod;
    @XmlElement(name = "outputFile", namespace = "http://www.brockmann-consult.de/calwps/calwpsL3Parameters-schema.xsd")
    protected String outputFile;

    public String getPlanetaryGrid() {
        return planetaryGrid;
    }

    public void setPlanetaryGrid(String planetaryGrid) {
        this.planetaryGrid = planetaryGrid;
    }

    public int getNumRows() {
        return numRows;
    }

    public void setNumRows(int numRows) {
        this.numRows = numRows;
    }

    public CompositingType getCompositingType() {
        return compositingType;
    }

    public void setCompositingType(CompositingType compositingType) {
        this.compositingType = compositingType;
    }

    public Integer getSuperSampling() {
        return superSampling;
    }

    public void setSuperSampling(Integer superSampling) {
        this.superSampling = superSampling;
    }

    public String getMaskExpr() {
        return maskExpr;
    }

    public void setMaskExpr(String maskExpr) {
        this.maskExpr = maskExpr;
    }

    public Variables getVariables() {
        return variables;
    }

    public void setVariables(Variables variables) {
        this.variables = variables;
    }

    public Aggregators getAggregators() {
        return aggregators;
    }

    public void setAggregators(Aggregators aggregators) {
        this.aggregators = aggregators;
    }

    public CellProcessorConfig getPostProcessorConfig() {
        return postProcessor;
    }

    public void setPostProcessorConfig(CellProcessorConfig postProcessor) {
        this.postProcessor = postProcessor;
    }

    public Double getMinDataHour() {
        return minDataHour;
    }

    public void setMinDataHour(Double minDataHour) {
        this.minDataHour = minDataHour;
    }

    public String getMetadataAggregatorName() {
        return metadataAggregatorName;
    }

    public void setMetadataAggregatorName(String metadataAggregatorName) {
        this.metadataAggregatorName = metadataAggregatorName;
    }

    public String getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(String startDateTime) {
        this.startDateTime = startDateTime;
    }

    public Double getPeriodDuration() {
        return periodDuration;
    }

    public void setPeriodDuration(Double periodDuration) {
        this.periodDuration = periodDuration;
    }

    public TimeFilterMethod getTimeFilterMethod() {
        return timeFilterMethod;
    }

    public void setTimeFilterMethod(TimeFilterMethod timeFilterMethod) {
        this.timeFilterMethod = timeFilterMethod;
    }

    public String getOutputFile() {
        return outputFile;
    }

    public void setOutputFile(String outputFile) {
        this.outputFile = outputFile;
    }
}
